### PR TITLE
Ported to ESP32

### PR DESCRIPTION
**Pull request by tantive**
-Ported to esp32. homie-esp8266 now supports architectures esp32 and esp8266.
-Successfully tested with M5Stick/Environment Sensor (https://docs.m5stack.com/#/en/core/m5stick, https://docs.m5stack.com/#/en/unit/env) on openHAB 2.4 / mosquitto 1.4.15.
-For increased openhab2.4 compatibility $stats/interval is now set correctly and published on every stats update (see https://github.com/eclipse/smarthome/issues/6495).
-On esp32 OTA and LED support are currently not working (future work needs to be done, see #FIXME comments).

### CODE REVIEW

**Comment by jeanvdr** [comment]
Hi,
I've got some trouble getting your library to work on a Lolin32. If I use the v1.0.1 esp32 core, I can compile homie sketchs but spiffs upload (arduino spiffs upload plugin doesn't work) or save doesn't work, when the board goes from config mode to normal mode, I've got a spiffs mounting problem and the board reboots untill it goes again in config mode. I've read there's a problem between spiffs and core 1.0.1. When I use esp32 core 1.0.0, I can use the arduino spiffs upload plugin, but I can't compile homie sketchs anymore because of a lot of compile errors in the asyncTCP library (again already described in the github issues of this library). Which version of these librairy did you use to get it work ?
Thanks a lot

**Comment by jeanvdr** [comment]
Ok, when I use your asyncTCP library found on github, I can compile homie sketches, but saving configuration through the web page configuration doesn't work (spiffs mounting problem on reboot). I have to upload the config.json file with the arduino spiffs upload plugin to get it work

**Comment by jeanvdr** [comment]
After some research, with esp32 core 1.0.1 and lastest asyncTCP librairy, you have to change in file config.cpp line 13:
_spiffsBegan = SPIFFS.begin(); -> _spiffsBegan = SPIFFS.begin(true);
the webconfig works and no more crash on reboots

**Comment by tantive** [comment]
@jeanvdr: Thanks a lot, I just committed your bugfix.

**Comment by jeanvdr** [comment]
It works for the first config but there is still a problem remaining. If you want to reboot in config mode (to change your configuration) you can either push the flash button if it exists or ground GPIO0 for several seconds. In this case, the ESP32 goes again in a neverending cycle of reboots...

**Comment by jeanvdr** [comment]
So, I can confirm the ota_updater (ota on mqtt) works on this esp32 version without the md5 checksum check. It seems the getmd5sketch function will probably not be developped for the esp32 infrastructure since there is a sha256 algorithm natively developped by Expressif.

**Comment by jeanvdr** [comment]
Sorry, I was wrong, the getSketchMD5 exists in the ESP32 core (esp.cpp) since 12/2018. I will try to use it this afternoon.

**Pull request closed without merging**
